crafter:
    security:
        accessDenied:
            error:
                url: /login?login_permission_error=true
        login:
            failure:
                url: /login?login_error=true
            form:
                url: /login
            success:
                url: /
        logout:
            success:
                url: /login?logout=true
        urlsToExclude: /resources/**
        urlsToInclude: /**
    profile:
        rest:
            client:
                accessToken:
                    id: 2ba3ac10-c43e-11e3-9c1a-0800200c9a66
                url:
                    base: http://localhost:8080/crafter-profile
social:
    management:
        name: crafter-social
        rootUrl: "http://localhost"
        date-format: MM/dd/yyyy HH:mm:ss
        folderPath: .
        overrideLocation: file*:${social.management.folderPath}/social-services-context.xml
        server:
              port: 8668
              contextPath: /crafter-social-admin/
              log:
                dir: ${social.management.folderPath}/logs
                name: social.log
                accesslog:
                        enable: false
# Spring Boot Properties

server:
  port: ${social.management.server.port}
  context-path: ${social.management.server.contextPath}
  undertow:
    accesslog:
      enabled: ${social.management.server.log.accesslog.enable}
      dir: ${social.management.server.log.dir}
logging:
  file: ${social.management.server.log.dir}/${social.management.server.log.name}
  level:
    org:
      craftercms:
        security: TRACE
      springframework:
        web: TRACE